// <auto-generated />
namespace Alborz.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editPriceTbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editPriceTbl));
        
        string IMigrationMetadata.Id
        {
            get { return "202010070525407_editPriceTbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
